### ISSUE TITLE
publish.sh failed with error in spreadsheet

### ISSUE THREAD

**Issue by jiaola** [HOT-Ecosystem/fhir#1]
Here's the error message: 
```
     [java] FHIR Infrastructure:
     [java]   CapabilityStatement(5), DomainResource(5), ImplementationGuide(1), OperationDefinition(5), Resource(5), SearchParameter(3), StructureMap(2)
     [java]  1.664  25sec  998MB
     [java] ERROR @ EightBall.answer: The short description "P1 | P2 | P3 | P4 | P5 | P6 | P7 | P8 | P9 | P10 | U1 | U2 | U3 | U4 | U5 | N1 | N2 | N3 | N4 | N5" does not match the expected ("Y | P1 | P2 | P3 | P4 | P5 | P6 | P7 | P8 | P9 | P10 | N1 | N2 | N3 | N4 | N5 | U | U1 | U2 | U3 | U4 | U5") (src = ResourceValidator)
     [java] This was a Full Build                                                      0.101  25sec  998MB
     [java] java.lang.Exception: Errors executing build. Details logged.
     [java] 	at org.hl7.fhir.tools.publisher.Publisher.checkAllOk(Publisher.java:1852)
     [java] 	at org.hl7.fhir.tools.publisher.Publisher.validate(Publisher.java:1838)
     [java] 	at org.hl7.fhir.tools.publisher.Publisher.execute(Publisher.java:621)
     [java] 	at org.hl7.fhir.tools.publisher.Publisher.main(Publisher.java:487)
     [java] FHIR build failure @ Fri, May 1, 2020 06:36-0400                           2.232  27sec  998MB
     [java] Error: Errors executing build. Details logged.
```

**Comment by jiaola** [comment]
Fixed here: 

https://github.com/HOT-Ecosystem/fhir/commit/4dadef7aa7345c807424c843cc4504a2e2fb2c77#diff-e6990b1aadf866d27ca9085d168fd19bR848
