### ISSUE TITLE
publish.sh failed with error in eightball-example.xml

### ISSUE THREAD

**Issue by jiaola** [HOT-Ecosystem/fhir#2]
Error message: 

     [java] Summary: Errors=4, Warnings=15566, Information messages=7085
     [java] ERROR @ EightBall.answer (line 0, col0): eightball-example:: EightBall.answer: ele-1: All FHIR elements must have a @value or children [hasValue() or (children().count() > id.count())] (src = InstanceValidator)
     [java] ERROR @ EightBall.answer (line 0, col0): eightball-example:: EightBall.answer: Primitive types must have a value or must have child extensions (src = InstanceValidator)
     [java] ERROR @ /Users/djiao1/Projects/hot-ecosystem/fhir/publish/eightball-example.xml (line 9, col22): eightball-example:: /Users/djiao1/Projects/hot-ecosystem/fhir/publish/eightball-example.xml: cvc-complex-type.2.4.a: Invalid content was found starting with element 'value'. One of '{"http://hl7.org/fhir":extension}' is expected. (src = InstanceValidator)
     [java] ERROR @ EightBall: eightball-example:: EightBall: Profile http://hl7.org/fhir/StructureDefinition/EightBall, Element 'EightBall.answer': minimum required = 1, but only found 0 (src = InstanceValidator)
     [java] This was a Full Build                                                      50.549 2241sec 1381MB

**Comment by hsolbrig** [comment]
Don't know whether this is the same message, but adding detail:
```
 [java] ERROR @ EightBall.answer (line 0, col0): eightball-example:: EightBall.answer: The value provided ("P1") is not in the value set http://hl7.org/fhir/ValueSet/eightball|4.2.0 (http://hl7.org/fhir/ValueSet/eightball), and a code is required from this value set) (error message = CodeSystem uri 'http://example.org/magic8ball' is unknown) (src = TerminologyEngine)
     [java] ERROR @ Bundle.entry[107].resource.ofType(CodeSystem): valuesets:: Bundle.entry[107].resource.ofType(CodeSystem): CodeSystem http://example.org/magic8ball has an 'all system' value set of http://hl7.org/fhir/ValueSet/eightball, but it is an expansion (src = InstanceValidator)
     [java] This was a Full Build                                                      54.728 17244sec 1383MB
     [java] FHIR build failure @ Fri, May 8, 2020 12:15-0500                            0.12 17244sec 1383MB
     [java] Error: Resource Examples failed instance validation
     [java] org.hl7.fhir.tools.publisher.ExampleInspector$EValidationFailed: Resource Examples failed instance validation
     [java] 	at org.hl7.fhir.tools.publisher.ExampleInspector.summarise(ExampleInspector.java:409)
     [java] 	at org.hl7.fhir.tools.publisher.Publisher.validationProcess(Publisher.java:5904)
     [java] 	at org.hl7.fhir.tools.publisher.Publisher.execute(Publisher.java:631)
     [java] 	at org.hl7.fhir.tools.publisher.Publisher.main(Publisher.java:487)

BUILD FAILED
/Users/solbrig/git/HOT-Ecosystem/fhir/build.xml:30: The following error occurred while executing this line:
/Users/solbrig/git/HOT-Ecosystem/fhir/tools/java/org.hl7.fhir.tools.core/build.xml:70: Java returned: 1
```
